services:
  domoticz:
    image: domoticz/domoticz:stable
    container_name: domoticz
    restart: unless-stopped
    # Pass devices to container
    # devices:
    #   - "/dev/serial/by-id/usb-0658_0200-if00-port0:/dev/ttyACM0"
    ports:
      - "8080:8080"
    volumes:
      - ./config:/opt/domoticz/userdata
      #- ./config/www/templates:/opt/domoticz/www/templates
    environment:
      - TZ=America/Argentina/Buenos_Aires
      #- LOG_PATH=/opt/domoticz/userdata/domoticz.log

